services:
  spring-security-demo:
    container_name: spring-security-demo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/security-database
      DATABASE_USER: joaob
      DATABASE_PASSWORD: 12345
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres-database
    image: postgres:latest
    environment:
      POSTGRES_DB: security-database
      POSTGRES_USER: joaob
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"