spring:
  application:
    name: spring-security-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  security:
    user:
      name: user
      password: 12345
  docker:
    compose:
      enabled: false