spring:
  application:
    name: spring-security-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  security:
    user:
      name: user
      password: 12345
    jwt:
      secret: ${JWT_SECRET:my-secret-key}