spring:
  application:
    name: spring-security-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./database
    username: sa
    password:
  h2:
    console:
      enabled: true